### ISSUE TITLE
Suggestion: mouse clicking

### ISSUE THREAD

**Issue by elig0n** [Boruch-Baum/morc_menu#10]
using the mouse to interact with menu

**Comment by Boruch-Baum** [comment]
On 2020-04-15 23:01, Eliran Gonen wrote:
>    using the mouse to interact with menu

That is a very desirable feature for many people, and does exist in many
other menuing programs, but it isn't possible for morc_menu itself to
implement. The reason for that is because morc_menu isn't itself a
menuing program; it's designed to be a feature enhancing front-end to
menuing programs such as dmenu, rofi, and maybe even zenity. If/when any
of those programs add mouse support, then morc_menu should automatically
have it without any software patching. It's been years since I worked on
this project, but back then the people behind dmenu and rofi seemed to
be ideologically keyboard-loving mouse-haters (ref: ratpoison tiling
window manager).

--
hkp://keys.gnupg.net
CA45 09B5 5351 7C11 A9D1  7286 0036 9E45 1595 8BC0

**Comment by oberon-manjaro** [comment]
I just found that **dmenu-manjaro**'s mouse-support patch has apparently stopped working. I have just applied an updated patch which will hopefully fix that again.

**Comment by oberon-manjaro** [comment]
Fixed with **dmenu-manjaro 4.9-5**

**Comment by Boruch-Baum** [comment]
Thanks!

--
hkp://keys.gnupg.net
CA45 09B5 5351 7C11 A9D1  7286 0036 9E45 1595 8BC0

**Comment by elig0n** [comment]
Confirmed. Thanks!
