### ISSUE TITLE
Keep It Simple, Stupid

### ISSUE THREAD

**Issue by pickfire** [Boruch-Baum/morc_menu#2]
Hi, I saw morc_menu on suckless, I wonder how can morc_menu be runned.

By the way, are morc_menu mksh compatible? (mksh is faster than bash)

**Comment by Boruch-Baum** [comment]
[quote]Hi, I saw morc_menu on suckless, I wonder how can morc_menu be runned.[/quote]
Thanks for writing. The instructions for running morc_menu are on the project main page README.md, section SETUP, and there are also links there to the wiki page which has a readable version of the man page. 

[quote]By the way, are morc_menu mksh compatible? (mksh is faster than bash)[/quote]
I'm not familiar with mksh. I suspect that the script uses many features specific to bash. You see, although bash is the slowest of all shells to load, if you use it correctly your scripts will run quicker because bash can do so many things internally for which other shells need to spawn sub processes. This isn't really a place for this kind of discussion, so my simple direct answer to your question is - I don't know, and you are probably correct if you mean that mksh loads its process faster than bash.

Are you available possibly to translate morc_menu and its documentation into another language? I see that one distribution has already included it in their development build iso for their next release, so there is some interest out there.

**Comment by zavok** [comment]
Yeah, looks like it uses some bash-specific syntax.

**Comment by pickfire** [comment]
Thanks it works now, I hope that you can refer to the commit which fix this as a good practice, eg. `#2` or `#138ab3`.

Yeah, I can help to translate it to chinese.

I acutally did a benchmark and it seems like mksh is faster. It goes by `mksh < fish < bash < zsh`.

I can say that the wiki looks bad in the current state. I hope that you can let others edit it, I can help to make it look a bit like https://github.com/fisherman/fisherman/wiki.

**Comment by Boruch-Baum** [comment]
Chinese would be awesome! It would also test the script in that language with that langauge's unicode and keyboard entry methods. Are you using morc_menu with Chinese characters now? You know, let's wait a few weeks on the translation, because depending upon feedback issues the original English may change. I would love to hear now, though, if morc_menu works in Chinese.

That's god to know about mksh, etc. Thanks.

You''re correct, of course, about the wiki. The project was posted two days ago, and I've been concentrating on the code, and the possibilities of fixing bugs, tweaking options and defaults, etc. I like the way the fisherman wiki looks, and once the project settles in, it's good to know that I can turn to you for help.

I didn't understand what you meant when you wrote, "I hope that you can refer to the commit which fix this as a good practice, eg. #2 or #138ab3". Could you explain that, please.

**Comment by pickfire** [comment]
It depends on dmenu, currently, my dmenu can display it but can't navigate over it.

By the way, st isn't shown in the menu, when I respond with `st`, it refuses to start st. I hope that it can check it.

In addition, is there some caching mechanism? Starting morc_menu is about as slow as dmenu, it is almost 3s.

> I didn't understand what you meant when you wrote, "I hope that you can refer to the commit which fix this as a good practice, eg. #2 or #138ab3". Could you explain that, please.

I mean to just say `I have implemented this in #2` instead of `Done`.

**Comment by Boruch-Baum** [comment]
"I mean to just say I have implemented this in #2 instead of Done."
That's still not clear. Also, I don't understand what you mean " st isn't shown in the menu, when I respond with st, it refuses to start st. I hope that it can check it." - What is "st"?

Your report about the delay of three seconds is important because there is another issue on that subject - issue $5. What do you mean exactly when you say "Starting morc_menu is about as slow as dmenu,"? Do you mean that dmenu is always that slow, even for other uses?

As to your question about caching, yes. If you look at the options, you will see that you can create and use a 'static' menu, one that will not update and change automatically when a new package is added or removed. You create a static menu using the command 'morc_menu build', and you use that static menu by calling  command 'morc_menu txt'. The script has many other options and configuration settings, so please read the man page and the configuration file carefully.

Please post to issue #5 any details about the delayed response of morc_menu. So far, you are the second person to report that the delay exists, but others see no delay ever. I don't get a delay.

**Comment by pickfire** [comment]
Dmenu is slow probably because there is about 3000 lines in the path.

`st` is [simple terminal](st.suckless.org), it is in the suckless project.

The delay exists because I am using rpi2.
