### ISSUE TITLE
vanilla dmenu doesn't have -x -y -w arguments

### ISSUE THREAD

**Issue by zavok** [Boruch-Baum/morc_menu#3]
Subj. And dmenu won't start if it encounters arguments it doesn't expect.
Attached is a naive "fix", but it's probably not a proper way of doing things.
[path.txt](https://github.com/Boruch-Baum/morc_menu/files/172308/path.txt)

**Comment by Boruch-Baum** [comment]
Honestly, your note was a jaw-dropper. I had unknowingly been working with a version of dmenu that was packaged as dmenu-manjaro, but not marked as an altered version. I've contacted the developer, and will very quickly modify the project README.md and other documentation..

The good news is that the design of the script makes this not a big deal to "fix" for use-cases that are locked into using only the real (what you call "vanilla") version of dmenu. The correct "fix" is the lines of your patch, but not in the file into which you patched it - make the change in the morc_menu configuration file. That's why its there.

I'm marking this as a serious bug in documentation / representation / dependency-claim / and default setting, and will start working on it now.

**Comment by Boruch-Baum** [comment]
I've pushed updates to the default settings, and to the documentation, so that morc_menu works with vanilla dmenu by default, and if people are using dmenu_manjaro they can easily uncomment a line in the configuration file to enjoy the benefits of the added bloat. Please let me know if you have any further trouble, or notice anything else amiss.

**Comment by oberon-manjaro** [comment]
Hi. Maintainer of **dmenu-manjaro** here :smiley: 
The added "bloat" we are tallking about here is the **xyw-patch** for dmenu position and width. It's nothing more than 30 lines of code, available from [suckless.org](http://tools.suckless.org/dmenu/patches/xyw) :stuck_out_tongue_closed_eyes:

**Comment by Boruch-Baum** [comment]
That's a riot! Then why do the developers insist on keeping it an external patch instead of integrating a very useful feature? That's really a question for them, and of their judgement. I went ahead and dumb-ed down the morc_menu defaults because they're stingy over 30 lines of code, written I think in C, isn't it? And we're not talking about anything requiring heavy processing or I/O. Is there a way to programmatically identify whether a version of dmenu has the patch? If so, I could auto-magically apply or deny features without forcing the user to deal with the versioning issue. As it stands, neither version of dmenu have a correct --version command; both just output text identical to --help. I'll try posting to dmenu now. If you agree, I'd welcome you joining in to coordinate and input your whatever your opinion is.

**Comment by oberon-manjaro** [comment]
I wonder if **morc_menu** actually needs the [line height patch](http://tools.suckless.org/dmenu/patches/line-height) (which has also been applied to dmenu-manjaro) too to make `line_height=` in morc_menu_v1.config work?

**Comment by Boruch-Baum** [comment]
I made my changes to defaults presuming that mor_menu would require that patch, so the current defaults (for vanilla dmenu) do not use line height.

Also, I already posted to dev@suckless.org, the mailing list for dmenu.

As I was writing to suckless.org, I came up with an idea to make life easy for users on the configuration side, but possibly more confusing on the experience side, and its pretty-high overhead compared to the rest of the script. I could have the script run 'dmenu --help' and then parse the output for that particular version of dmenu's list of valid parameters. Then, the script could prune invalid parameters from the user's desired command. The result would be a simpler config file with need for fewer examples, but on the other hand would require an explanation of why features being requested aren't being honored. What do you think?

**Comment by oberon-manjaro** [comment]
hm. interesting idea :smiley: 
I'm still a fan of morc_menu creating its own .config file in **~/.config** at first run. It could possibly even be created based on the available option from `dmenu --help` :stuck_out_tongue_closed_eyes: 
Only: What happens when the user updates or switches his front-end? Or decides to suddenly use a different version of dmenu... how would morc_menu know that and adjust an existing .config file? It gets a bit complicated ;)
Maybe an easy and clean way will just be to list the 'advances' settings together with their requirements, like:
`use_mouse_position=TRUE        # requires xdotools and/or ...`
...

**Comment by Boruch-Baum** [comment]
My idea would be to check upon run-time, so any change in the front-end being used would be accounted for. While I have decided to adopt the idea of -copying- the morc_menu config file to the the user's config directory, I wouldn't want morc_menu to start customizing it over what the sysadmin had done to the version in the system-wide config folder.
From what I've looked into your 'clean' suggestion, it seems to me to end up not being clean, because it still ends up requiring either the user edit the menu_cmd variable or the script to intelligently prune it.
