### ISSUE TITLE
use_mouse_position not working

### ISSUE THREAD

**Issue by elig0n** [Boruch-Baum/morc_menu#9]
set to true, even commented x&y_position, yet shows the menu at a constant place to the far right of my screen irregardless of where the mouse cursor is actually at.

morc_menu  Version 1.0, 2016-03-18
on Manjaro Linux

**Comment by Boruch-Baum** [comment]
Wow. It's great to get feedback on this after so many years. I'm not
currently using manjaro (a phenomenal disto run by a great team), but
I'll try to help.

1) Please confirm that you are using the dmenu-manjaro version of dmenu.
   When I wrote morc_menu, that specific version was a dependency
   because it included patches to support to mouse-postion feature. If
   package dmenu-manjaro no longer exists, or if the xy patch is no
   longer part of it, that would be the source of your problem. In that
   case, you could ask team manjaro to either re-apply the patch, or to
   point you to the relevant historical version.

2) Please tell me the exact value of the config variable menu_cmd.

--
hkp://keys.gnupg.net
CA45 09B5 5351 7C11 A9D1  7286 0036 9E45 1595 8BC0

**Comment by elig0n** [comment]
> 1) Please confirm that you are using the dmenu-manjaro version of dmenu. When I wrote morc_menu, that specific version was a dependency because it included patches to support to mouse-postion feature. If package dmenu-manjaro no longer exists, or if the xy patch is no longer part of it, that would be the source of your problem. In that case, you could ask team manjaro to either re-apply the patch, or to point you to the relevant historical version.

dmenu-manjaro still exists and I'm using version 4.9-4.
According to the [PKGBUILD](https://gitlab.manjaro.org/packages/community/dmenu-manjaro/blob/master/PKGBUILD) `mousesupport`, `line-height` and `xyw` patches are applied.

> 2) Please tell me the exact value of the config variable menu_cmd.

    menu_cmd="dmenu -i -l MENU_LINES -x X_POSITION -y Y_POSITION -w MENU_WIDTH ${DMENU_OPTIONS} "

**Comment by Boruch-Baum** [comment]
Eliran: Did you see the post from Bernhard Landauer ("Oberon") on your
related issue #10. He says that the issue should be fixed in a new
version: dmenu-manjaro 4,9-5. Does that software update resolve this
issue for you?

--
hkp://keys.gnupg.net
CA45 09B5 5351 7C11 A9D1  7286 0036 9E45 1595 8BC0

**Comment by elig0n** [comment]
It does. Thanks!
